[package]
name = "esperanto-server"
version = "0.1.0"
edition = "2024"

[dependencies]
esperanto-core = { path = "../esperanto-core" }

tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = "1.0"
serde_json = "1.0"
tower = "0.5.2"
hyper = "1.6.0"
