[package]
name = "esperanto"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "esperanto-server",
    "esperanto-core"
]

# Optional: You can define shared profiles for all members
[profile.release]
lto = true
codegen-units = 1
strip = true